### ISSUE TITLE
dont start

### ISSUE THREAD

**Issue by JumperOnJava** [ricardosouzag/ModInstaller#119]
where logs
game version 1.5.78.11833
windows 10

**Comment by Imasake** [comment]
Same, also doesn't work with 1.4.9.2.

**Comment by OndrejL81** [comment]
Still dont work (dec 2021)

**Comment by HeWhoThreadsLightly** [comment]
Null pointer exception when trying to start the second to newest version, newest one does not give an error before it exits.

************** Exception Text **************
System.ArgumentNullException: Value cannot be null.
Parameter name: uriString
   at System.Uri..ctor(String uriString)
   at ModInstaller.ModManager.CheckApiInstalled()
   at ModInstaller.ModManager.Form2_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by osu4GBRAM** [comment]
Downgrade to beta 32-bit compatability. You can look up a guide for that.

**Comment by JumperOnJava** [comment]
Wait what

**Comment by JumperOnJava** [comment]
Oh i made this issue
